<?php
/**
 * City data for WordPress theme
 * Synced from src/data/cityData.ts — 138 cities
 */

$drw_cities = array(
    // Tier 1 — Metro Cities
    array('name' => 'Delhi', 'slug' => 'delhi', 'state' => 'Delhi', 'tier' => 1),
    array('name' => 'Mumbai', 'slug' => 'mumbai', 'state' => 'Maharashtra', 'tier' => 1),
    array('name' => 'Bangalore', 'slug' => 'bangalore', 'state' => 'Karnataka', 'tier' => 1),
    array('name' => 'Chennai', 'slug' => 'chennai', 'state' => 'Tamil Nadu', 'tier' => 1),
    array('name' => 'Kolkata', 'slug' => 'kolkata', 'state' => 'West Bengal', 'tier' => 1),
    array('name' => 'Hyderabad', 'slug' => 'hyderabad', 'state' => 'Telangana', 'tier' => 1),
    array('name' => 'Pune', 'slug' => 'pune', 'state' => 'Maharashtra', 'tier' => 1),
    array('name' => 'Ahmedabad', 'slug' => 'ahmedabad', 'state' => 'Gujarat', 'tier' => 1),
    // Tier 1 — NCR
    array('name' => 'Gurgaon', 'slug' => 'gurgaon', 'state' => 'Haryana', 'tier' => 1),
    array('name' => 'Noida', 'slug' => 'noida', 'state' => 'Uttar Pradesh', 'tier' => 1),
    array('name' => 'Ghaziabad', 'slug' => 'ghaziabad', 'state' => 'Uttar Pradesh', 'tier' => 1),
    array('name' => 'Faridabad', 'slug' => 'faridabad', 'state' => 'Haryana', 'tier' => 1),
    array('name' => 'Greater Noida', 'slug' => 'greater-noida', 'state' => 'Uttar Pradesh', 'tier' => 1),

    // Tier 2 — North India
    array('name' => 'Lucknow', 'slug' => 'lucknow', 'state' => 'Uttar Pradesh', 'tier' => 2),
    array('name' => 'Jaipur', 'slug' => 'jaipur', 'state' => 'Rajasthan', 'tier' => 2),
    array('name' => 'Chandigarh', 'slug' => 'chandigarh', 'state' => 'Chandigarh', 'tier' => 2),
    array('name' => 'Amritsar', 'slug' => 'amritsar', 'state' => 'Punjab', 'tier' => 2),
    array('name' => 'Ludhiana', 'slug' => 'ludhiana', 'state' => 'Punjab', 'tier' => 2),
    array('name' => 'Kanpur', 'slug' => 'kanpur', 'state' => 'Uttar Pradesh', 'tier' => 2),
    array('name' => 'Agra', 'slug' => 'agra', 'state' => 'Uttar Pradesh', 'tier' => 2),
    array('name' => 'Varanasi', 'slug' => 'varanasi', 'state' => 'Uttar Pradesh', 'tier' => 2),
    array('name' => 'Prayagraj', 'slug' => 'prayagraj', 'state' => 'Uttar Pradesh', 'tier' => 2),
    array('name' => 'Dehradun', 'slug' => 'dehradun', 'state' => 'Uttarakhand', 'tier' => 2),
    array('name' => 'Meerut', 'slug' => 'meerut', 'state' => 'Uttar Pradesh', 'tier' => 2),
    array('name' => 'Patna', 'slug' => 'patna', 'state' => 'Bihar', 'tier' => 2),
    array('name' => 'Ranchi', 'slug' => 'ranchi', 'state' => 'Jharkhand', 'tier' => 2),
    array('name' => 'Bhopal', 'slug' => 'bhopal', 'state' => 'Madhya Pradesh', 'tier' => 2),
    array('name' => 'Indore', 'slug' => 'indore', 'state' => 'Madhya Pradesh', 'tier' => 2),
    array('name' => 'Jodhpur', 'slug' => 'jodhpur', 'state' => 'Rajasthan', 'tier' => 2),
    array('name' => 'Udaipur', 'slug' => 'udaipur', 'state' => 'Rajasthan', 'tier' => 2),
    array('name' => 'Kota', 'slug' => 'kota', 'state' => 'Rajasthan', 'tier' => 2),
    array('name' => 'Jalandhar', 'slug' => 'jalandhar', 'state' => 'Punjab', 'tier' => 2),
    array('name' => 'Patiala', 'slug' => 'patiala', 'state' => 'Punjab', 'tier' => 2),

    // Tier 2 — West India
    array('name' => 'Nagpur', 'slug' => 'nagpur', 'state' => 'Maharashtra', 'tier' => 2),
    array('name' => 'Nashik', 'slug' => 'nashik', 'state' => 'Maharashtra', 'tier' => 2),
    array('name' => 'Surat', 'slug' => 'surat', 'state' => 'Gujarat', 'tier' => 2),
    array('name' => 'Vadodara', 'slug' => 'vadodara', 'state' => 'Gujarat', 'tier' => 2),
    array('name' => 'Rajkot', 'slug' => 'rajkot', 'state' => 'Gujarat', 'tier' => 2),
    array('name' => 'Aurangabad', 'slug' => 'aurangabad', 'state' => 'Maharashtra', 'tier' => 2),
    array('name' => 'Thane', 'slug' => 'thane', 'state' => 'Maharashtra', 'tier' => 2),
    array('name' => 'Navi Mumbai', 'slug' => 'navi-mumbai', 'state' => 'Maharashtra', 'tier' => 2),
    array('name' => 'Goa', 'slug' => 'goa', 'state' => 'Goa', 'tier' => 2),

    // Tier 2 — South India
    array('name' => 'Coimbatore', 'slug' => 'coimbatore', 'state' => 'Tamil Nadu', 'tier' => 2),
    array('name' => 'Kochi', 'slug' => 'kochi', 'state' => 'Kerala', 'tier' => 2),
    array('name' => 'Thiruvananthapuram', 'slug' => 'thiruvananthapuram', 'state' => 'Kerala', 'tier' => 2),
    array('name' => 'Visakhapatnam', 'slug' => 'visakhapatnam', 'state' => 'Andhra Pradesh', 'tier' => 2),
    array('name' => 'Vijayawada', 'slug' => 'vijayawada', 'state' => 'Andhra Pradesh', 'tier' => 2),
    array('name' => 'Madurai', 'slug' => 'madurai', 'state' => 'Tamil Nadu', 'tier' => 2),
    array('name' => 'Mysore', 'slug' => 'mysore', 'state' => 'Karnataka', 'tier' => 2),
    array('name' => 'Mangalore', 'slug' => 'mangalore', 'state' => 'Karnataka', 'tier' => 2),
    array('name' => 'Hubli', 'slug' => 'hubli', 'state' => 'Karnataka', 'tier' => 2),
    array('name' => 'Tirupati', 'slug' => 'tirupati', 'state' => 'Andhra Pradesh', 'tier' => 2),
    array('name' => 'Warangal', 'slug' => 'warangal', 'state' => 'Telangana', 'tier' => 2),

    // Tier 2 — East India
    array('name' => 'Bhubaneswar', 'slug' => 'bhubaneswar', 'state' => 'Odisha', 'tier' => 2),
    array('name' => 'Guwahati', 'slug' => 'guwahati', 'state' => 'Assam', 'tier' => 2),
    array('name' => 'Jamshedpur', 'slug' => 'jamshedpur', 'state' => 'Jharkhand', 'tier' => 2),
    array('name' => 'Siliguri', 'slug' => 'siliguri', 'state' => 'West Bengal', 'tier' => 2),

    // Tier 3 — North India
    array('name' => 'Bareilly', 'slug' => 'bareilly', 'state' => 'Uttar Pradesh', 'tier' => 3),
    array('name' => 'Aligarh', 'slug' => 'aligarh', 'state' => 'Uttar Pradesh', 'tier' => 3),
    array('name' => 'Moradabad', 'slug' => 'moradabad', 'state' => 'Uttar Pradesh', 'tier' => 3),
    array('name' => 'Gorakhpur', 'slug' => 'gorakhpur', 'state' => 'Uttar Pradesh', 'tier' => 3),
    array('name' => 'Mathura', 'slug' => 'mathura', 'state' => 'Uttar Pradesh', 'tier' => 3),
    array('name' => 'Muzaffarnagar', 'slug' => 'muzaffarnagar', 'state' => 'Uttar Pradesh', 'tier' => 3),
    array('name' => 'Saharanpur', 'slug' => 'saharanpur', 'state' => 'Uttar Pradesh', 'tier' => 3),
    array('name' => 'Firozabad', 'slug' => 'firozabad', 'state' => 'Uttar Pradesh', 'tier' => 3),
    array('name' => 'Jhansi', 'slug' => 'jhansi', 'state' => 'Uttar Pradesh', 'tier' => 3),
    array('name' => 'Haridwar', 'slug' => 'haridwar', 'state' => 'Uttarakhand', 'tier' => 3),
    array('name' => 'Rishikesh', 'slug' => 'rishikesh', 'state' => 'Uttarakhand', 'tier' => 3),
    array('name' => 'Haldwani', 'slug' => 'haldwani', 'state' => 'Uttarakhand', 'tier' => 3),
    array('name' => 'Roorkee', 'slug' => 'roorkee', 'state' => 'Uttarakhand', 'tier' => 3),
    array('name' => 'Shimla', 'slug' => 'shimla', 'state' => 'Himachal Pradesh', 'tier' => 3),
    array('name' => 'Jammu', 'slug' => 'jammu', 'state' => 'Jammu & Kashmir', 'tier' => 3),
    array('name' => 'Srinagar', 'slug' => 'srinagar', 'state' => 'Jammu & Kashmir', 'tier' => 3),
    array('name' => 'Panipat', 'slug' => 'panipat', 'state' => 'Haryana', 'tier' => 3),
    array('name' => 'Karnal', 'slug' => 'karnal', 'state' => 'Haryana', 'tier' => 3),
    array('name' => 'Hisar', 'slug' => 'hisar', 'state' => 'Haryana', 'tier' => 3),
    array('name' => 'Rohtak', 'slug' => 'rohtak', 'state' => 'Haryana', 'tier' => 3),
    array('name' => 'Sonipat', 'slug' => 'sonipat', 'state' => 'Haryana', 'tier' => 3),
    array('name' => 'Ambala', 'slug' => 'ambala', 'state' => 'Haryana', 'tier' => 3),
    array('name' => 'Bhiwani', 'slug' => 'bhiwani', 'state' => 'Haryana', 'tier' => 3),
    array('name' => 'Bathinda', 'slug' => 'bathinda', 'state' => 'Punjab', 'tier' => 3),
    array('name' => 'Pathankot', 'slug' => 'pathankot', 'state' => 'Punjab', 'tier' => 3),
    array('name' => 'Gwalior', 'slug' => 'gwalior', 'state' => 'Madhya Pradesh', 'tier' => 3),
    array('name' => 'Jabalpur', 'slug' => 'jabalpur', 'state' => 'Madhya Pradesh', 'tier' => 3),
    array('name' => 'Ujjain', 'slug' => 'ujjain', 'state' => 'Madhya Pradesh', 'tier' => 3),
    array('name' => 'Raipur', 'slug' => 'raipur', 'state' => 'Chhattisgarh', 'tier' => 3),
    array('name' => 'Bilaspur', 'slug' => 'bilaspur', 'state' => 'Chhattisgarh', 'tier' => 3),
    array('name' => 'Bikaner', 'slug' => 'bikaner', 'state' => 'Rajasthan', 'tier' => 3),
    array('name' => 'Ajmer', 'slug' => 'ajmer', 'state' => 'Rajasthan', 'tier' => 3),
    array('name' => 'Alwar', 'slug' => 'alwar', 'state' => 'Rajasthan', 'tier' => 3),
    array('name' => 'Bhilwara', 'slug' => 'bhilwara', 'state' => 'Rajasthan', 'tier' => 3),
    array('name' => 'Sikar', 'slug' => 'sikar', 'state' => 'Rajasthan', 'tier' => 3),
    array('name' => 'Muzaffarpur', 'slug' => 'muzaffarpur', 'state' => 'Bihar', 'tier' => 3),
    array('name' => 'Gaya', 'slug' => 'gaya', 'state' => 'Bihar', 'tier' => 3),
    array('name' => 'Bhagalpur', 'slug' => 'bhagalpur', 'state' => 'Bihar', 'tier' => 3),
    array('name' => 'Darbhanga', 'slug' => 'darbhanga', 'state' => 'Bihar', 'tier' => 3),
    array('name' => 'Purnia', 'slug' => 'purnia', 'state' => 'Bihar', 'tier' => 3),

    // Tier 3 — West India
    array('name' => 'Kolhapur', 'slug' => 'kolhapur', 'state' => 'Maharashtra', 'tier' => 3),
    array('name' => 'Solapur', 'slug' => 'solapur', 'state' => 'Maharashtra', 'tier' => 3),
    array('name' => 'Sangli', 'slug' => 'sangli', 'state' => 'Maharashtra', 'tier' => 3),
    array('name' => 'Ahmednagar', 'slug' => 'ahmednagar', 'state' => 'Maharashtra', 'tier' => 3),
    array('name' => 'Bhavnagar', 'slug' => 'bhavnagar', 'state' => 'Gujarat', 'tier' => 3),
    array('name' => 'Jamnagar', 'slug' => 'jamnagar', 'state' => 'Gujarat', 'tier' => 3),
    array('name' => 'Junagadh', 'slug' => 'junagadh', 'state' => 'Gujarat', 'tier' => 3),
    array('name' => 'Anand', 'slug' => 'anand', 'state' => 'Gujarat', 'tier' => 3),

    // Tier 3 — South India
    array('name' => 'Salem', 'slug' => 'salem', 'state' => 'Tamil Nadu', 'tier' => 3),
    array('name' => 'Tiruchirappalli', 'slug' => 'tiruchirappalli', 'state' => 'Tamil Nadu', 'tier' => 3),
    array('name' => 'Erode', 'slug' => 'erode', 'state' => 'Tamil Nadu', 'tier' => 3),
    array('name' => 'Vellore', 'slug' => 'vellore', 'state' => 'Tamil Nadu', 'tier' => 3),
    array('name' => 'Thoothukudi', 'slug' => 'thoothukudi', 'state' => 'Tamil Nadu', 'tier' => 3),
    array('name' => 'Kozhikode', 'slug' => 'kozhikode', 'state' => 'Kerala', 'tier' => 3),
    array('name' => 'Thrissur', 'slug' => 'thrissur', 'state' => 'Kerala', 'tier' => 3),
    array('name' => 'Kannur', 'slug' => 'kannur', 'state' => 'Kerala', 'tier' => 3),
    array('name' => 'Guntur', 'slug' => 'guntur', 'state' => 'Andhra Pradesh', 'tier' => 3),
    array('name' => 'Nellore', 'slug' => 'nellore', 'state' => 'Andhra Pradesh', 'tier' => 3),
    array('name' => 'Kurnool', 'slug' => 'kurnool', 'state' => 'Andhra Pradesh', 'tier' => 3),
    array('name' => 'Rajahmundry', 'slug' => 'rajahmundry', 'state' => 'Andhra Pradesh', 'tier' => 3),
    array('name' => 'Karimnagar', 'slug' => 'karimnagar', 'state' => 'Telangana', 'tier' => 3),
    array('name' => 'Nizamabad', 'slug' => 'nizamabad', 'state' => 'Telangana', 'tier' => 3),
    array('name' => 'Belgaum', 'slug' => 'belgaum', 'state' => 'Karnataka', 'tier' => 3),
    array('name' => 'Davangere', 'slug' => 'davangere', 'state' => 'Karnataka', 'tier' => 3),
    array('name' => 'Bellary', 'slug' => 'bellary', 'state' => 'Karnataka', 'tier' => 3),
    array('name' => 'Shimoga', 'slug' => 'shimoga', 'state' => 'Karnataka', 'tier' => 3),

    // Tier 3 — East & Northeast India
    array('name' => 'Cuttack', 'slug' => 'cuttack', 'state' => 'Odisha', 'tier' => 3),
    array('name' => 'Rourkela', 'slug' => 'rourkela', 'state' => 'Odisha', 'tier' => 3),
    array('name' => 'Sambalpur', 'slug' => 'sambalpur', 'state' => 'Odisha', 'tier' => 3),
    array('name' => 'Bokaro', 'slug' => 'bokaro', 'state' => 'Jharkhand', 'tier' => 3),
    array('name' => 'Dhanbad', 'slug' => 'dhanbad', 'state' => 'Jharkhand', 'tier' => 3),
    array('name' => 'Asansol', 'slug' => 'asansol', 'state' => 'West Bengal', 'tier' => 3),
    array('name' => 'Durgapur', 'slug' => 'durgapur', 'state' => 'West Bengal', 'tier' => 3),
    array('name' => 'Dibrugarh', 'slug' => 'dibrugarh', 'state' => 'Assam', 'tier' => 3),
    array('name' => 'Jorhat', 'slug' => 'jorhat', 'state' => 'Assam', 'tier' => 3),
    array('name' => 'Imphal', 'slug' => 'imphal', 'state' => 'Manipur', 'tier' => 3),
    array('name' => 'Agartala', 'slug' => 'agartala', 'state' => 'Tripura', 'tier' => 3),
    array('name' => 'Shillong', 'slug' => 'shillong', 'state' => 'Meghalaya', 'tier' => 3),
    array('name' => 'Aizawl', 'slug' => 'aizawl', 'state' => 'Mizoram', 'tier' => 3),
    array('name' => 'Gangtok', 'slug' => 'gangtok', 'state' => 'Sikkim', 'tier' => 3),
    array('name' => 'Itanagar', 'slug' => 'itanagar', 'state' => 'Arunachal Pradesh', 'tier' => 3),
);
